name: CI (Linux, container)

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04          # le runner host importe peu ici
    container:
      image: swift:6.2-noble       # outilchain Swift 6.2 sur Ubuntu 24.04 (noble)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install D-Bus headers
        run: apt-get update && apt-get install -y libdbus-1-dev pkg-config

      - name: Debug toolchain & dbus
        run: |
          swift --version
          pkg-config --modversion dbus-1

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v

